security:
    providers:
        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

#        secured_area:
#            pattern: ^/
#            stateless: true
#            simple_preauth:
#                authenticator: api_key_authenticator
#            provider: api_key_user_provider
